<a href="https://colab.research.google.com/github/vinaysk125/vinayassingment/blob/main/LinearDiscriminantAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [ ]:
from google.colab import drive
drive.mount("/content/drive", force_remount = True)

Mounted at /content/drive

In [ ]:
df = pd.read_csv("/content/drive/My Drive/CHDdata.csv")
df.head()

   sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
0  160    12.00  5.73      23.11  Present     49    25.30    97.20   52    1
1  144     0.01  4.41      28.61   Absent     55    28.87     2.06   63    1
2  118     0.08  3.48      32.28  Present     52    29.14     3.81   46    0
3  170     7.50  6.41      38.03  Present     51    31.99    24.26   58    1
4  134    13.60  3.50      27.78  Present     60    25.99    57.34   49    1

In [ ]:
df1 = df.loc[:, ["age", "chd"]]
df1.head()

   age  chd
0   52    1
1   63    1
2   46    0
3   58    1
4   49    1

In [ ]:
X = df1.iloc[:, :-1].values
Y = df.iloc[:, -1].values

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
lda.fit(X, Y)
y_pred = lda.predict(X)

In [ ]:
lda.decision_function(X)

array([-0.17390512,  0.509484  , -0.54666282,  0.19885258, -0.36028397,
       -0.6087891 , -1.04367309,  0.19885258, -1.60280964, -0.11177883,
        0.32310515, -0.91942052, -2.34832504, -2.47257761, -0.11177883,
       -0.54666282, -0.36028397, -0.11177883,  0.44735772,  0.26097887,
       -2.16194619, -0.67091539, -0.29815768,  0.19885258, -0.29815768,
       -0.79516795, -0.42241025,  0.38523143,  0.07460002,  0.509484  ,
       -0.6087891 , -0.54666282,  0.26097887, -0.85729424, -0.42241025,
       -1.66493592, -1.41643079, -0.54666282, -1.60280964,  0.19885258,
       -0.85729424, -1.54068336, -2.47257761, -0.2360314 , -2.34832504,
       -0.42241025,  0.19885258, -1.3543045 , -2.41045132, -1.54068336,
       -0.79516795, -0.36028397, -0.79516795, -1.47855707, -0.11177883,
       -0.42241025, -1.66493592, -1.04367309, -2.28619876,  0.38523143,
       -1.3543045 , -0.67091539,  0.1367263 , -1.04367309, -2.34832504,
       -0.04965255, -1.54068336, -1.72706221, -1.3543045 , -1.41643079,
       -2.47257761, -1.78918849, -1.16792565, -2.16194619, -1.29217822,
       -0.91942052,  0.01247373,  0.01247373,  0.07460002, -0.9815468 ,
       -0.6087891 , -0.11177883,  0.01247373,  0.1367263 , -2.34832504,
       -0.6087891 , -0.36028397, -1.04367309, -0.85729424,  0.01247373,
       -2.09981991,  0.57161028, -1.60280964, -0.36028397,  0.07460002,
        0.44735772, -1.60280964, -0.9815468 , -0.2360314 , -0.9815468 ,
       -0.29815768, -1.72706221, -0.54666282, -1.47855707, -1.60280964,
        0.57161028,  0.38523143, -0.04965255, -0.79516795, -2.28619876,
       -2.41045132, -0.04965255, -1.10579937,  0.38523143,  0.26097887,
       -0.42241025, -1.41643079, -0.79516795,  0.38523143, -1.72706221,
        0.32310515, -1.66493592, -1.3543045 ,  0.07460002, -0.6087891 ,
        0.26097887, -1.66493592, -1.04367309,  0.32310515,  0.57161028,
        0.44735772,  0.19885258, -1.54068336, -0.04965255, -0.91942052,
       -0.17390512, -1.41643079, -1.66493592, -2.16194619, -0.04965255,
       -0.04965255, -1.85131477, -1.04367309,  0.19885258, -0.91942052,
       -0.91942052, -1.47855707, -0.73304167, -1.3543045 ,  0.38523143,
        0.01247373, -0.17390512, -1.91344106, -2.16194619, -0.85729424,
        0.01247373, -2.34832504, -0.11177883, -1.04367309, -0.73304167,
       -1.47855707,  0.44735772, -2.41045132, -2.09981991, -2.41045132,
       -0.36028397,  0.01247373, -0.73304167, -1.85131477, -0.42241025,
       -0.85729424, -1.41643079, -0.48453654,  0.38523143,  0.44735772,
        0.38523143, -1.10579937, -2.34832504, -1.91344106,  0.07460002,
        0.07460002, -0.2360314 ,  0.32310515, -0.9815468 , -0.42241025,
       -1.3543045 ,  0.509484  , -0.9815468 ,  0.509484  ,  0.57161028,
       -0.91942052, -0.36028397, -0.9815468 , -1.97556734, -2.28619876,
       -2.09981991, -2.34832504, -0.79516795, -0.04965255, -1.72706221,
       -1.97556734, -1.47855707, -1.3543045 ,  0.57161028,  0.19885258,
       -0.91942052, -2.28619876,  0.32310515,  0.26097887,  0.32310515,
        0.32310515, -0.91942052, -0.67091539, -0.11177883, -2.28619876,
        0.44735772, -0.6087891 , -1.78918849, -1.85131477,  0.1367263 ,
       -2.41045132, -0.54666282,  0.32310515, -0.6087891 ,  0.07460002,
       -0.79516795, -1.41643079, -0.17390512,  0.57161028, -0.29815768,
        0.19885258,  0.44735772,  0.19885258, -1.54068336, -1.60280964,
       -0.2360314 ,  0.38523143,  0.1367263 , -1.72706221, -2.41045132,
       -0.6087891 , -0.48453654, -0.85729424,  0.01247373,  0.32310515,
        0.1367263 ,  0.07460002,  0.32310515,  0.57161028,  0.19885258,
       -0.42241025, -2.34832504,  0.509484  , -0.79516795, -0.54666282,
       -0.04965255, -1.10579937, -0.36028397,  0.19885258, -0.67091539,
       -2.34832504, -2.16194619,  0.38523143, -1.23005194, -0.17390512,
       -2.28619876, -2.34832504,  0.1367263 , -2.41045132, -0.6087891 ,
        0.01247373, -0.85729424, -1.91344106, -0.73304167,  0.01247373,
        0.509484  ,  0.57161028, -0.73304167, -2.41045132, -2.41045132,
       -1.66493592, -0.79516795, -0.29815768, -1.72706221, -0.85729424,
       -2.34832504, -2.22407247, -2.34832504, -2.41045132, -1.04367309,
       -2.41045132, -2.41045132, -0.67091539,  0.07460002, -1.29217822,
       -0.79516795, -2.34832504, -2.34832504, -0.54666282, -0.11177883,
       -0.6087891 , -1.41643079, -0.11177883,  0.26097887, -1.72706221,
       -0.36028397, -0.6087891 ,  0.26097887, -1.10579937, -1.29217822,
        0.26097887, -0.54666282,  0.26097887, -0.67091539, -0.29815768,
        0.26097887, -1.04367309, -1.78918849,  0.26097887, -0.2360314 ,
        0.26097887, -1.04367309,  0.38523143,  0.57161028,  0.01247373,
       -1.16792565,  0.44735772, -2.22407247, -0.9815468 ,  0.01247373,
       -2.34832504, -0.6087891 , -0.2360314 ,  0.26097887,  0.26097887,
       -0.73304167,  0.19885258,  0.26097887, -1.72706221, -1.54068336,
       -0.91942052, -0.17390512, -0.11177883, -1.47855707, -1.10579937,
       -1.78918849, -0.11177883,  0.38523143, -0.73304167,  0.32310515,
       -0.36028397, -1.16792565,  0.19885258,  0.38523143, -0.04965255,
        0.19885258, -1.91344106, -0.36028397, -0.29815768, -1.41643079,
        0.44735772, -1.29217822, -0.42241025,  0.32310515, -0.17390512,
       -1.66493592, -1.91344106, -1.54068336, -1.04367309, -0.79516795,
        0.57161028, -0.85729424, -1.41643079,  0.57161028, -1.60280964,
       -0.6087891 , -1.47855707, -0.11177883, -1.04367309,  0.57161028,
       -0.17390512, -0.67091539, -1.04367309, -1.47855707, -0.67091539,
       -0.04965255,  0.26097887, -0.11177883, -1.78918849, -0.11177883,
       -0.9815468 , -0.29815768,  0.38523143,  0.57161028, -0.42241025,
       -1.72706221,  0.44735772, -0.42241025,  0.01247373, -0.48453654,
       -0.36028397, -0.36028397,  0.44735772,  0.19885258,  0.1367263 ,
       -0.2360314 ,  0.38523143,  0.32310515, -0.91942052, -2.41045132,
        0.44735772,  0.32310515,  0.01247373,  0.509484  , -0.54666282,
       -0.9815468 ,  0.32310515, -0.6087891 , -0.42241025, -0.85729424,
       -0.73304167,  0.509484  ,  0.01247373,  0.38523143, -0.79516795,
       -1.3543045 , -1.3543045 , -0.36028397, -1.29217822, -1.41643079,
       -2.41045132, -2.41045132, -2.41045132, -2.28619876, -2.41045132,
       -2.41045132, -2.34832504, -2.41045132, -1.47855707, -0.91942052,
       -1.41643079, -2.41045132, -0.17390512, -1.10579937, -1.72706221,
       -1.85131477, -1.29217822, -2.34832504, -2.16194619, -0.42241025,
       -1.91344106, -2.28619876, -0.79516795, -0.2360314 , -0.9815468 ,
       -1.72706221,  0.1367263 ,  0.19885258, -0.17390512,  0.01247373,
       -0.91942052, -0.54666282])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_metrix = confusion_matrix(Y, y_pred)
print(confusion_metrix)

[[243  59]
 [ 89  71]]

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(Y, y_pred))

              precision    recall  f1-score   support

           0       0.73      0.80      0.77       302
           1       0.55      0.44      0.49       160

    accuracy                           0.68       462
   macro avg       0.64      0.62      0.63       462
weighted avg       0.67      0.68      0.67       462